# Generated by Django 4.2.13 on 2024-06-14 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dtCriacao', models.DateTimeField(auto_now_add=True)),
                ('dtUltimaAlt', models.DateTimeField(auto_now=True)),
                ('colaboradorAlt', models.CharField(blank=True, max_length=100, null=True)),
                ('estTicket', models.CharField(default='porAtender', max_length=50)),
                ('estAtendimento', models.CharField(default='Aberto', max_length=50)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('idColaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HardwareTicket',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tickets.ticket')),
                ('idHard', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('equipamento', models.CharField(blank=True, max_length=100, null=True)),
                ('avaria', models.TextField(blank=True, null=True)),
                ('descRep', models.TextField(blank=True, null=True)),
                ('pecas', models.TextField(blank=True, null=True)),
            ],
            bases=('tickets.ticket',),
        ),
        migrations.CreateModel(
            name='SoftwareTicket',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tickets.ticket')),
                ('idSoft', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('software', models.CharField(blank=True, max_length=100, null=True)),
                ('descNecessidade', models.TextField(blank=True, null=True)),
                ('descInt', models.TextField(blank=True, null=True)),
            ],
            bases=('tickets.ticket',),
        ),
    ]
