# Generated by Django 4.2.13 on 2024-06-14 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardwareticket',
            name='idHard',
        ),
        migrations.RemoveField(
            model_name='softwareticket',
            name='idSoft',
        ),
    ]
