# Generated by Django 4.2.13 on 2024-06-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_hardwareticket_idhard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='estAtendimento',
            field=models.CharField(blank=True, choices=[('aberto', 'Aberto'), ('resolvido', 'Resolvido'), ('naoResolvido', 'Não Resolvido')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estTicket',
            field=models.CharField(choices=[('porAtender', 'Por Atender'), ('emAtendimento', 'Em Atendimento'), ('atendido', 'Atendido')], default='porAtender', max_length=50),
        ),
    ]
